routes/main_routes.py
from flask import render_template, Blueprint, request, session, redirect, url_for, flash
from flask_login import login_required, current_user
from config import Config
from models import User
import sqlite3
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import random
import string

main_routes = Blueprint('main_routes', __name__)

def get_cart_items():
    return session.get('cart', [])

def calculate_total(cart_items):
    return sum(item['price'] * item['quantity'] for item in cart_items)

@main_routes.route('/')
def index():
    with sqlite3.connect(Config.DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute('''SELECT name, price, category, image FROM products''')
        products = cursor.fetchall()
    return render_template('index.html', products=products)

@main_routes.route('/my_orders')
@login_required
def my_orders():
    orders = User.get_user_orders_with_items(current_user.id)
    return render_template('my_orders.html', orders=orders)

@main_routes.route('/cart', methods=['GET', 'POST'])
@login_required
def cart():
    if request.method == 'POST':
        product_name = request.form.get('product_name')
        product_price = float(request.form.get('product_price'))
        product_type = request.form.get('product_type')

        if 'cart' not in session:
            session['cart'] = []

        cart = session['cart']

        found = False
        for item in cart:
            if item['name'] == product_name:
                item['quantity'] += 1
                found = True
                break

        if not found:
            cart.append({
                'name': product_name,
                'price': product_price,
                'product_type': product_type,
                'quantity': 1
            })

        session['cart'] = cart
        session.modified = True
        return redirect(url_for('main_routes.index'))

    cart_items = session.get('cart', [])
    total = calculate_total(cart_items)
    return render_template('cart.html', cart_items=cart_items, total=total)

@main_routes.route('/clear_cart')
@login_required
def clear_cart():
    session.pop('cart', None)
    return redirect(url_for('main_routes.cart'))

@main_routes.route('/view_order', methods=['POST', 'GET'])
@login_required
def order():
    cart_items = get_cart_items()
    total = calculate_total(cart_items)
    return render_template('intouch.html', cart_items=cart_items, total=total)

def generate_order_number(length=6):
    characters = string.ascii_uppercase + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

@main_routes.route('/checkout', methods=['POST'])
@login_required
def checkout():
    cart_items = session.get('cart', [])
    email = request.form['email']
    phone = request.form['phone']
    address = request.form['address']
    delivery = request.form['delivery_option']
    order_number = generate_order_number()
    status = 'Курьер забрал заказ и направляется к вам'

    with sqlite3.connect(Config.DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute('''INSERT INTO orders (user_id, status) VALUES (?, ?)''', (current_user.id, status))
        order_id = cursor.lastrowid

        for item in cart_items:
            cursor.execute('''INSERT INTO order_items (order_id, name, price, quantity) VALUES (?, ?, ?, ?)''', (order_id, item['name'], item['price'], item['quantity']))

        conn.commit()

    session.pop('cart', None)
    return redirect(url_for('main_routes.view_order', order_id=order_id))

@main_routes.route('/view_order/<int:order_id>')
@login_required
def view_order(order_id):
    with sqlite3.connect(Config.DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute('SELECT id, status FROM orders WHERE id = ?', (order_id,))
        order = cursor.fetchone()
        if order is None:
            flash("Заказ не найден!", "error")
            return redirect(url_for('main_routes.index'))

        cursor.execute('SELECT name, price, quantity FROM order_items WHERE order_id = ?', (order_id,))
        cart_items = cursor.fetchall()

    cart_items = [
        {
            'name': item[0],
            'price': float(item[1]),
            'quantity': item[2],
            'total_price': float(item[1]) * item[2]
        }
        for item in cart_items
    ]
    total = sum(item['total_price'] for item in cart_items)

    return render_template('intouch.html', order_number=order[0], status=order[1], cart_items=cart_items, total=total)

@main_routes.route('/update_quantity/<item_name>', methods=['POST'])
@login_required
def update_quantity(item_name):
    new_quantity = int(request.form['quantity'])
    for item in session['cart']:
        if item['name'] == item_name:
            item['quantity'] = new_quantity
            break
    session.modified = True
    return redirect(url_for('main_routes.cart'))

templates/cart.html
<head>
    <title>Корзина</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">
    <link rel="shortcut icon" href="../static/images/logo.png" sizes="32x32">
</head>
{% extends "output.html" %}
{% block content %}
    <div class="container">
        <a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a>
        <h2>Корзина</h2>
        <h1>Список товаров:</h1>
        <div class="cart-items">
            {% for item in cart_items %}
            <div class="cart-item">
                <p>{{ item.name }}</p>
                <p>{{ item.price }} руб.</p>
                <form method="post" action="{{ url_for('main_routes.update_quantity', item_name=item.name) }}">
                    <label for="quantity">Количество:</label>
                    <select name="quantity" onchange="this.form.submit()">
                        {% for i in range(1, 11) %}
                            <option value="{{ i }}" {% if item.quantity == i %}selected{% endif %}>{{ i }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            {% endfor %}
        </div>
        <div class="cart-summary">
            <div class="order">
                <form method="post" action="{{ url_for('main_routes.checkout') }}">
                    <label for="phone" style="text-align: center;">Номер телефона:</label>
                    <input type="text" id="phone" name="phone" required>
                    <label for="email" style="text-align: center;">Почта:</label>
                    <input type="email" id="email" name="email" required>
                    <label for="delivery_option" style="text-align: center;">Способ получения:</label>
                    <select id="delivery_option" name="delivery_option" onchange="toggleAddressField()">
                        <option value="Pickup">Самовывоз</option>
                        <option value="Delivery">Доставка</option>
                    </select>
                    <div id="address_field" style="display: none;">
                        <label for="address" style="text-align: center;">Адрес:</label>
                        <input type="text" id="address" name="address">
                    </div>
                    <button type="submit" class="checkout-btn">Оформить заказ</button>
                </form>
            </div>
            <br>
            <p>Итого: <span class="cart-total">{{ total }} руб.</span></p>
        </div>
        <div class="corsina">
            <form method="get" action="{{ url_for('main_routes.clear_cart') }}">
                <button type="submit" class="checkout-btn">Очистить корзину</button>
            </form>
            <br>
        </div>
    </div>
    <script src="../static/scripts/cart.js"></script>
{% endblock %}

templates/couriers.html
<link rel="stylesheet" href="{{ url_for('static', filename='style/panel.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style/cour.css') }}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
<title>Меню курьера</title>
{% extends "output.html" %}
{% block content %}
<div class="admin-container">
    <a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a>
    <h1>Все заказы</h1>
    <div class="admin-section">
        <table id="order-list">
            <thead>
                <tr>
                    <th>Номер заказа  </th>
                    <th class="status">Текущий статус</th>
                    <th>Изменить статус  </th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <td class="status">{{ order[0] }}</td>
                    <td class="status">{{ order[1] }}</td>
                    <td>
                        <br>
                        <form method="post">
                          <input type="hidden" name="order_id" value="{{ order[0] }}">
                          <select name="status">
                            {% for s in config.STATUS_LIST %}
                              <option value="{{ s }}" {% if s == order[1] %}selected{% endif %}>{{ s }}</option>
                            {% endfor %}
                          </select>
                          <button type="submit">Изменить статус</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
</html>

templates/index.html
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Доставка Еды в Ногинске</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/main.css') }}">
    <link rel="shortcut icon" href="../static/images/logo.png"/>
</head>
{% block content %}
    <header>
        <nav class="navbar">
            <div class="container">
                <div class="logotype">
                    <a href="#" class="logo">Kitchen Сloud</a>
                </div>
                <ul class="nav-links">
                    <li><a href="#home">Главная</a></li>
                    {% if current_user.is_authenticated and (current_user.is_courier == 'yes' or current_user.is_admin == 'yes') %}
                      <li><a href="{{ url_for('courier_routes.courier_panel') }}">Для курьеров</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated and (current_user.is_admin == 'yes') %}
                      <li><a href="{{ url_for('admin_routes.admin_panel') }}">Для администраторов</a></li>
                    {% endif %}
                    <li><a href="#menu">Меню</a></li>
                </ul>
                <div class="auth-cart">
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth_routes.logout') }}" class="auth-btn">Выйти</a>
                    {% else %}
                        <a href="{{ url_for('auth_routes.login') }}" class="auth-btn">Войти</a>
                    {% endif %}
                    <a id="cart-link" href="{{ url_for('main_routes.cart') }}" class="cart-btn">Корзина</a>
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('main_routes.my_orders') }}" class="cart-btn">Мои заказы</a>
                    {% endif %}

                </div>
            </div>
        </nav>
    </header>
    <section id="home" class="banner">
        <div class="overlay">
            <div class="container">
                <h1>Приветствуем Вас в Kitchen Cloud</h1>
                <br>
                <a href="#menu" class="cta-btn">Заказать сейчас</a>
            </div>
        </div>
    </section>
    <section id="menu" class="menu">
        <div class="container">
            <h2>Наше Меню</h2>
            <div class="category-buttons">
                <button onclick="filterProducts('all')">Все</button>
                <button onclick="filterProducts('Горячие блюда')">Горячие блюда</button>
                <button onclick="filterProducts('Завтраки')">Завтраки</button>
                <button onclick="filterProducts('Вторые блюда')">Вторые блюда</button>
                <button onclick="filterProducts('Салаты')">Салаты</button>
                <button onclick="filterProducts('Напитки')">Напитки</button>
            </div>
            <br>
            <div class="menu-categories">
                <ul id="product-list">
                {% for product in products %}
                    <li class="product" data-category="{{ product[2] }}">
                        <img src="{{ url_for('static', filename='uploads/' + product[3]) }}">
                        <br>
                        <h3>{{ product[0] }}</h3>
                        <p>Цена: {{ product[1] }} руб.</p>
                        <form method="post" action="{{ url_for('main_routes.cart') }}">
                            <input type="hidden" name="product_name" value="{{ product[0] }}">
                            <input type="hidden" name="product_price" value="{{ product[1] }}">
                            <input type="hidden" name="product_type" value="{{ product[2] }}">
                            <button type="submit" class="add-to-cart-btn">Добавить в корзину</button>
                        </form>
                    </li>
                {% endfor %}
            </div>
        </div>
    </section>
    <hr>
    <script src="../static/scripts/menu.js"></script>
    <section id="about" class="about">
        <div class="container">
            <h2>О нас</h2>
            <p> Kitchen Cloud — это ресторан высокого класса, который предлагает своим посетителям изысканные блюда, приготовленные с особой заботой о качестве и вкусе. Мы стремимся объединить традиционные рецепты с современными кулинарными техниками, чтобы каждый клиент мог насладиться уникальными блюдами в уютной обстановке. Наше меню включает разнообразные горячие блюда, завтраки, вторые блюда, салаты и напитки, что позволяет удовлетворить любые гастрономические предпочтения.
                Все наши блюда готовятся с использованием свежих ингредиентов, а внимание к деталям позволяет создавать блюда, которые не только вкусны, но и эстетичны. Мы заботимся о комфорте наших гостей, предлагая удобный онлайн-сервис для оформления и отслеживания заказов.<br></p>
        </div>
    </section>
    <hr>
    <footer>
        <div class="container footer-container">
            <div class="footer-column">
                <h3>О нас</h3>
                <ul>
                    <li><a href="#">О нас</a></li>
                    <li><a href="#">Наша команда</a></li>
                    <li><a href="#">Стань одним из нас</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Помощь</h3>
                <ul>
                    <li><a href="#faq">Частые вопросы</a></li>
                    <li><a href="#support">Поддержка</a></li>
                    <li><a href="#contact">Контакты</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Мы в социальных сетях</h3>
                <ul>
                    <li><a href="https://facebook.com" target="_blank">Facebook</a></li>
                    <li><a href="https://instagram.com" target="_blank">Instagram</a></li>
                    <li><a href="https://twitter.com" target="_blank">Twitter</a></li>
                </ul>
            </div>
        </div>
        <br>
        <br>
        <div class="container">
            <p>&copy;Курсовая работа Юманов Евгений 2025 Ногинск.</p>
        </div>
    </footer>
{% endblock %}

templates/intouch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Статус заказа</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style/panel.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/cour.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
</head>
<body>
    <div class="container">
        <h1>Статус заказа</h1>
        <div class="order-info">
            <p><strong>Номер заказа:</strong> {{ order_number }}</p>
            <p><strong>Статус заказа:</strong> {{ status }}</p>
        </div>
        <h2>Вы заказали:</h2>
        <div class="cart-items">
            {% for item in cart_items %}
            <div class="cart-item">
                <div class="cart-item-details">
                    <p><strong>{{ item.name }}</strong></p>
                    <p>Цена за единицу: {{ item.price }} руб.</p>
                    <p>Количество: {{ item.quantity }}</p>
                    <p>Сумма позиции: {{ item.total_price }} руб.</p>
                </div>
            </div>
            {% endfor %}
        </div>
    <div class="cart-summary">
          <p><strong>Общая сумма: {{ total }} руб.</strong></p>
    </div>
    <button><a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a></button>
</div>

</body>
</html>

templates/login.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
</head>
{% extends "output.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">

<div class="container auth-container">
    <p><a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a></p>
    <h2>Авторизация</h2>
    <br>
    <form action="{{ url_for('auth_routes.login') }}" method="post" class="auth-form">
        <label for="username">Имя пользователя</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Пароль</label>
        <input type="password" id="password" name="password" required>
        <button type="submit" class="auth-btn">Войти</button>
    </form>
    <br>
    <p>Ещё не с нами? <a href="{{ url_for('auth_routes.register') }}">Регистрация</a></p>
</div>
{% endblock %}

templates/my_orders.html
{% extends "output.html" %}
{% block content %}
<div class="admin-container">
  <a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a>
  <h1>Мои заказы</h1>
  <div class="admin-section">
    <table id="order-list">
      <thead>
        <tr>
          <th>Номер заказа</th>
          <th>Дата создания</th>
          <th>Статус</th>
          <th>Общая сумма</th>
          <th>Состав заказа</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ order.id }}</td>
          <td>{{ order.created_at }}</td>
          <td>{{ order.status }}</td>
          <td>{{ order.total }} ₽</td>
          <td>
            <ul>
              {% for item in order['items'] %}
              <li>{{ item.name }} - {{ item.price }}₽ x {{ item.quantity }}</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if not orders %}
      <p>У вас пока нет заказов.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/output.html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{ url_for('static', filename='style/panel.css') }}">
<link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
<main>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="flash-messages">
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</main>

templates/panel.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Панель Администратора.</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/panel.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">
    <link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
</head>
{% extends "output.html" %}
{% block content %}
<div class="admin-container">
    <p><a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a></p>
    <h1>Добро пожаловать, {{ current_user.username }}.</h1>
    <div class="admin-sections">
        <div class="admin-section">
            <h2>Товары</h2>
            <br>
            <form action="{{ url_for('admin_routes.create_product') }}" method="post" enctype="multipart/form-data">
                <input type="text" name="product_name" placeholder="Название товара" required>
                <input type="number" name="product_price" placeholder="Цена товара" required>
                <label for="category">Категория товара</label>
                <select name="category">
                    <option value="Горячие блюда">Горячие блюда</option>
                    <option value="Завтраки">Завтраки</option>
                    <option value="Вторые блюда">Вторые блюда</option>
                    <option value="Салаты">Салаты</option>
                    <option value="Напитки">Напитки</option>
                </select>
                <label for="product_image" class="file-input-label">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M0 0h24v24H0z" fill="none"/>
                        <path d="M15.5 13.59l-4.17-4.17L6 15.25V20h4.75l5.42-5.42zM18 4h-3.5l-2-2H7c-1.1 0-1.99.9-1.99 2L5 18c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 14H7V6h3.5l2 2H18v10z"/>
                    </svg>
                    <span>Выберите изображение продукта</span>
                </label>
                <input type="file" id="product_image" name="product_image" required accept="image/png, image/jpeg" style="display: none;">
                <button type="submit" name="action4" value="create">Добавить товар</button>
                <button type="submit" name="action4" value="delete">Удалить товар</button>
            </form>
            <ul class="product-list">
            </ul>
        </div>
        <div class="admin-section">
            <h2>Курьеры</h2>
            <br>
            <form action="{{ url_for('admin_routes.change_courier_status') }}" method="post">
                <input type="text" name="courier_username" placeholder="Имя пользователя" required>
                <input type="password" name="courier_password" placeholder="Пароль" required>
                <button type="submit">Создать учетную запись курьера</button>
            </form>
            <ul class="courier-list">
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="../static/images/logo.png"/ sizes="32x32">
</head>
{% extends "output.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style/cart.css') }}">
<div class="container auth-container">
    <a href="{{ url_for('main_routes.index') }}" class="home-link">На главную</a>
    <h2>Регистрация</h2>
    <br>
    <form action="{{ url_for('auth_routes.register') }}" method="post" class="auth-form">
        <label for="username">Имя пользователя</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Пароль</label>
        <input type="password" id="password" name="password" required>
        <button type="submit" class="auth-btn">Зарегистрироваться</button>
    </form>
    <br>
    <p>Уже есть аккаунт? <a href="{{ url_for('auth_routes.login') }}">Войти</a></p>
</div>
{% endblock %}